# Generated by Django 4.1.5 on 2023-02-08 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FileCNAB', '0002_alter_filecnab_cpf_alter_filecnab_cartão_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filecnab',
            old_name='cartão',
            new_name='cartao',
        ),
    ]
