# Generated by Django 4.1.5 on 2023-02-08 13:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FileCNAB', '0003_rename_cartão_filecnab_cartao'),
    ]

    operations = [
        migrations.AddField(
            model_name='filecnab',
            name='natureza',
            field=models.TextField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
