# Generated by Django 4.1.5 on 2023-02-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileCNAB', '0004_filecnab_natureza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filecnab',
            name='CPF',
            field=models.TextField(max_length=11),
        ),
        migrations.AlterField(
            model_name='filecnab',
            name='cartao',
            field=models.TextField(max_length=12),
        ),
        migrations.AlterField(
            model_name='filecnab',
            name='hora',
            field=models.TextField(max_length=6),
        ),
        migrations.AlterField(
            model_name='filecnab',
            name='tipo',
            field=models.TextField(max_length=1),
        ),
        migrations.AlterField(
            model_name='filecnab',
            name='valor',
            field=models.TextField(max_length=10),
        ),
    ]
